SegPerfAnalyzer: CAnalyzer Class Reference
CAnalyzer Class Reference
Class to compute various metrics to evaluate segmentation results.
#include "Class to compute various metrics to evaluate segmentation results."
Public Member Functions
CAnalyzer (char *pi_pchImageTestName, char *pi_pchImageRefName, bool advancedEvaluation)
Constructor.
~CAnalyzer ()
void setNbThreads (int pi_iNbThreads)
Set the number of threads to use for the computation of ITK.
void selectCluster (unsigned int)
Select the cluster we want to use to compute evaluation results.
void setDetectionThresholdAlpha (double pi_fVal)
void setDetectionThresholdBeta (double pi_fVal)
void setDetectionThresholdGamma (double pi_fVal)
void setMinLesionVolumeDetection (double pi_fVal)
float computeHausdorffDist ()
Compute Haussdorf distance.
float computeMeanDist ()
Compute mean distance.
float computeAverageSurfaceDistance ()
Compute average surface distance.
void computeITKMeasures ()
Compute different measures with ITK to evaluate segmentation.
float getUnionOverlap ()
Getter of Union overlap.
float getMeanOverlap ()
Getter of Mean overlap.
float getSensitivity ()
Getter of Sensibility.
float getSpecificity ()
Getter of Specificity.
float getPPV ()
Getter of Positive predictive value.
float getNPV ()
Getter of Negative predictive value.
float getDiceCoefficient ()
Getter of Dice coefficient.
float getJaccardCoefficient ()
Getter of Jaccard coefficient.
float getRelativeVolumeError ()
Getter of Relative volume error.
bool getDetectionMarks (float &po_fPPVL, float &po_fSensL, float &po_fF1)
Compute useful variables to get detection scores.
int getNumberOfClusters ()
Return the number of clusters.
Protected Member Functions
void formatLabels ()
Format labels values for the image to evaluate and the ground truth to obtain : background pixels values = 0, cluster 1 pixels values = 1 ...etc.
void contourDectection ()
Extract the contour of the image to evaluate and the ground truth.
void checkNumberOfLabels (int, int)
Check if the number of labels is the same for both input images.
int getTruePositiveLesions (int pi_iNbLabelsRef, int pi_iNbLabelsTest, int **pi_ppiOverlapTab)
Getter of True positive lesions.
bool falsePositiveRatioTester (int pi_iLessionReference, int pi_iNbLabelsTest, int pi_iNbLabelsRef, int **pi_ppiOverlapTab, int *pi_piTPRowSumTab, int *pi_piColumnSumTab, double pi_dfBeta, double pi_dfGamma)
Compute if a lesion is detected or not with beta and gamma thresholds.
void getOverlapTab (int &po_iNbLabelsRef, int &po_iNbLabelsTest, int **&po_ppiOverlapTab)
Compute a table of lesion overlap between 2 images.
Private Types
typedef itk::Image< unsigned
short, 3 > ImageType
typedef itk::ImageFileReader
< ImageType > ImageReaderType
typedef
itk::ImageRegionConstIterator
< ImageType > ImageIteratorType
typedef
itk::SegmentationMeasuresImageFilter
< ImageType > FilterType
Private Member Functions
CAnalyzer ()
void transposer (int pi_iNbLabelsRef, int pi_iNbLabelsTest, int **pi_ppiOverlapTab, int **&po_rppiOverlapTabTransposed)
Compute a transposed table of lesion overlap between 2 images from the original table. It inverse reference image and tested image.
void removeOverlapTab (int **pi_ppiOverlapTab, int pi_iNbLabelsRef)
Remove a table of lesion overlap between 2 images.
Private Attributes
unsigned int m_uiNbLabels
bool m_bValuesComputed
bool m_bContourDetected
double m_dfDetectionThresholdAlpha
double m_dfDetectionThresholdBeta
double m_dfDetectionThresholdGamma
double m_dfMinLesionVolumeDetection
ImageType::Pointer m_imageTest
ImageType::Pointer m_imageRef
ImageType::Pointer m_imageTestContour
ImageType::Pointer m_imageRefContour
ImageType::Pointer m_imageRefDuplicated
ImageType::Pointer m_imageTestDuplicated
FilterType::Pointer m_oFilter
itk::ThreadIdType m_ThreadNb
Detailed Description
Class to compute various metrics to evaluate segmentation results.
Definition at line 36 of file Analyzer.h.
Member Typedef Documentation
typedef itk::SegmentationMeasuresImageFilter<ImageType> CAnalyzer::FilterType private
Definition at line 55 of file Analyzer.h.
typedef itk::ImageRegionConstIterator<ImageType> CAnalyzer::ImageIteratorType private
Definition at line 54 of file Analyzer.h.
typedef itk::ImageFileReader<ImageType> CAnalyzer::ImageReaderType private
Definition at line 53 of file Analyzer.h.
typedef itk::Image<unsigned short, 3> CAnalyzer::ImageType private
Definition at line 52 of file Analyzer.h.
Constructor & Destructor Documentation
CAnalyzer::CAnalyzer (char * pi_pchImageTestName, char * pi_pchImageRefName, bool bAdvancedEvaluation)
Constructor.
Read input images
Parameters
[in] pi_pchImageTestName Name of the image to evaluate
[in] pi_pchImageRefName Name of the ground truth image
[in] bAdvancedEvaluation
Definition at line 32 of file Analyzer.cpp.
CAnalyzer::~CAnalyzer ()
Definition at line 107 of file Analyzer.cpp.
CAnalyzer::CAnalyzer () private
Definition at line 21 of file Analyzer.cpp.
Member Function Documentation
void CAnalyzer::checkNumberOfLabels (int iNbLabelsImageTest, int iNbLabelsImageRef) protected
Check if the number of labels is the same for both input images.
Definition at line 353 of file Analyzer.cpp.
float CAnalyzer::computeAverageSurfaceDistance ()
Compute average surface distance.
Returns
average surface distance
Definition at line 625 of file Analyzer.cpp.
Referenced by CSegPerfApp::processAnalyze().
float CAnalyzer::computeHausdorffDist ()
Compute Haussdorf distance.
Returns
hausdorffDistance in float
Definition at line 552 of file Analyzer.cpp.
Referenced by CSegPerfApp::processAnalyze().
void CAnalyzer::computeITKMeasures ()
Compute different measures with ITK to evaluate segmentation.
Definition at line 235 of file Analyzer.cpp.
Referenced by CSegPerfApp::processAnalyze().
float CAnalyzer::computeMeanDist ()
Compute mean distance.
Returns
meanDistance
Definition at line 587 of file Analyzer.cpp.
Referenced by CSegPerfApp::processAnalyze().
void CAnalyzer::contourDectection () protected
Extract the contour of the image to evaluate and the ground truth.
Definition at line 179 of file Analyzer.cpp.
bool CAnalyzer::falsePositiveRatioTester (int pi_iLesionReference, int pi_iNbLabelsTest, int pi_iNbLabelsRef, int ** pi_ppiOverlapTab, int * pi_piTPRowSumTab, int * pi_piColumnSumTab, double pi_dfBeta, double pi_dfGamma) protected
Compute if a lesion is detected or not with beta and gamma thresholds.
Parameters
[out] pi_iLesionReference the number of labels found by connected components into reference image (1 by connected component + 1 for the background).
[out] pi_iNbLabelsTest the number of labels found by connected components into tested image (1 by connected component + 1 for the background).
[out] pi_iNbLabelsRef the number of the label of the tested lesion.
[out] pi_ppiOverlapTab the mapping table.
[out] pi_piTPRowSumTab the table of sum of Rows.
[out] pi_piColumnSumTab the table of sum of Columns.
[out] pi_dfBeta the beta threshold.
[out] pi_dfGamma the beta threshold.
Returns
true if the lesion is detected, false in other cases.
Definition at line 948 of file Analyzer.cpp.
void CAnalyzer::formatLabels () protected
Format labels values for the image to evaluate and the ground truth to obtain : background pixels values = 0, cluster 1 pixels values = 1 ...etc.
Definition at line 439 of file Analyzer.cpp.
bool CAnalyzer::getDetectionMarks (float & po_fPPVL, float & po_fSensL, float & po_fF1)
Compute useful variables to get detection scores.
Parameters
[out] po_fFNL the output FNL (False Negative Lesions) ratio.
[out] po_fFPL the output FPL (False Positive Lesions) ratio.
[out] po_fPPVL the output PPVL (Positive Predictive Value for Lesions) ratio.
[out] po_fSensL the output SensL, Lesion detection sensitivity ratio.
[out] po_fF1 the output F1_score.
Returns
true
Definition at line 720 of file Analyzer.cpp.
Referenced by CSegPerfApp::processAnalyze().
float CAnalyzer::getDiceCoefficient ()
Getter of Dice coefficient.
Returns
Dice coefficient in float
Definition at line 327 of file Analyzer.cpp.
Referenced by CSegPerfApp::processAnalyze().
float CAnalyzer::getJaccardCoefficient ()
Getter of Jaccard coefficient.
Returns
Jaccard coefficient in float
Definition at line 336 of file Analyzer.cpp.
Referenced by CSegPerfApp::processAnalyze().
float CAnalyzer::getMeanOverlap ()
Getter of Mean overlap.
Returns
Mean overlap in float
Definition at line 282 of file Analyzer.cpp.
float CAnalyzer::getNPV ()
Getter of Negative predictive value.
Returns
Negative predictive value in float
Definition at line 318 of file Analyzer.cpp.
Referenced by CSegPerfApp::processAnalyze().
int CAnalyzer::getNumberOfClusters ()
Return the number of clusters.
Returns
Number of clusters
Definition at line 115 of file Analyzer.cpp.
void CAnalyzer::getOverlapTab (int & po_iNbLabelsRef, int & po_iNbLabelsTest, int **& po_ppiOverlapTab) protected
Compute a table of lesion overlap between 2 images.
Parameters
[out] po_iNbLabelsRef the number of labels found by connected components into reference image (1 by connected component + 1 for the background).
[out] po_iNbLabelsTest the number of labels found by connected components into tested image (1 by connected component + 1 for the background).
[out] po_ppiOverlapTab the table allocated by this method. Dimensions are po_iNbLabelsTest*po_iNbLabelsRef. The first cell [0][0] is the number of True-Negative voxels (background in both images), first line (excepte first cell) are False-Posite voxels, first colomne are False-Negative voxels and the rest of cels are True positive voxels. In Other words: first line is the back ground into Ref-image, first column is the back ground into Tested-image and the element [i][j] (with i,j > 0) correspond to the number of voxel belonging to the label i, that overlap with a voxel of the label j.
Definition at line 781 of file Analyzer.cpp.
float CAnalyzer::getPPV ()
Getter of Positive predictive value.
Returns
Positive predictive value in float
Definition at line 309 of file Analyzer.cpp.
Referenced by CSegPerfApp::processAnalyze().
float CAnalyzer::getRelativeVolumeError ()
Getter of Relative volume error.
Returns
Relative volume error in float
Definition at line 345 of file Analyzer.cpp.
Referenced by CSegPerfApp::processAnalyze().
float CAnalyzer::getSensitivity ()
Getter of Sensibility.
Returns
Sensibility in float
Definition at line 291 of file Analyzer.cpp.
Referenced by CSegPerfApp::processAnalyze().
float CAnalyzer::getSpecificity ()
Getter of Specificity.
Returns
Specificity in float
Definition at line 300 of file Analyzer.cpp.
Referenced by CSegPerfApp::processAnalyze().
int CAnalyzer::getTruePositiveLesions (int pi_iNbLabelsRef, int pi_iNbLabelsTest, int ** pi_ppiOverlapTab) protected
Getter of True positive lesions.
Returns
True positive lesions
Definition at line 879 of file Analyzer.cpp.
float CAnalyzer::getUnionOverlap ()
Getter of Union overlap.
Returns
Union overlap in float
Definition at line 273 of file Analyzer.cpp.
void CAnalyzer::removeOverlapTab (int ** pi_ppiOverlapTab, int pi_iNbLabelsRef) private
Remove a table of lesion overlap between 2 images.
Parameters
[in] pi_ppiOverlapTab the table to remove.
[in] pi_iNbLabelsRef the line dimension.
Definition at line 1019 of file Analyzer.cpp.
void CAnalyzer::selectCluster (unsigned int iCluster)
Select the cluster we want to use to compute evaluation results.
Parameters
[in] iCluster
Definition at line 124 of file Analyzer.cpp.
Referenced by CSegPerfApp::processAnalyze().
void CAnalyzer::setDetectionThresholdAlpha (double pi_fVal) inline
Definition at line 85 of file Analyzer.h.
References m_dfDetectionThresholdAlpha.
Referenced by CSegPerfApp::processAnalyze().
void CAnalyzer::setDetectionThresholdBeta (double pi_fVal) inline
Definition at line 90 of file Analyzer.h.
References m_dfDetectionThresholdBeta.
Referenced by CSegPerfApp::processAnalyze().
void CAnalyzer::setDetectionThresholdGamma (double pi_fVal) inline
Definition at line 95 of file Analyzer.h.
References m_dfDetectionThresholdGamma.
Referenced by CSegPerfApp::processAnalyze().
void CAnalyzer::setMinLesionVolumeDetection (double pi_fVal) inline
Definition at line 100 of file Analyzer.h.
References m_dfMinLesionVolumeDetection.
Referenced by CSegPerfApp::processAnalyze().
void CAnalyzer::setNbThreads (int pi_iNbThreads)
Set the number of threads to use for the computation of ITK.
Parameters
[in] pi_iNbThreads Number of threads.
Definition at line 770 of file Analyzer.cpp.
Referenced by CSegPerfApp::play().
void CAnalyzer::transposer (int pi_iNbLabelsRef, int pi_iNbLabelsTest, int ** pi_ppiOverlapTab, int **& po_rppiOverlapTabTransposed) private
Compute a transposed table of lesion overlap between 2 images from the original table. It inverse reference image and tested image.
Parameters
[in] pi_iNbLabelsRef the number of labels found by connected components into reference image (1 by connected component + 1 for the background).
[in] pi_iNbLabelsTest the number of labels found by connected components into tested image (1 by connected component + 1 for the background).
[in] pi_ppiOverlapTab the table allocated by this method. Dimensions are po_iNbLabelsTest*po_iNbLabelsRef.
[out] po_rppiOverlapTabTransposed the transposed table allocated by this method. Dimensions are po_iNbLabelsTest*po_iNbLabelsRef.
Definition at line 997 of file Analyzer.cpp.
Member Data Documentation
bool CAnalyzer::m_bContourDetected private
Boolean to check if contour detection have been done.
Definition at line 43 of file Analyzer.h.
bool CAnalyzer::m_bValuesComputed private
Boolean to check if values have been computed.
Definition at line 42 of file Analyzer.h.
double CAnalyzer::m_dfDetectionThresholdAlpha private
Definition at line 46 of file Analyzer.h.
Referenced by setDetectionThresholdAlpha().
double CAnalyzer::m_dfDetectionThresholdBeta private
Definition at line 47 of file Analyzer.h.
Referenced by setDetectionThresholdBeta().
double CAnalyzer::m_dfDetectionThresholdGamma private
Definition at line 48 of file Analyzer.h.
Referenced by setDetectionThresholdGamma().
double CAnalyzer::m_dfMinLesionVolumeDetection private
Definition at line 49 of file Analyzer.h.
Referenced by setMinLesionVolumeDetection().
ImageType::Pointer CAnalyzer::m_imageRef private
Definition at line 58 of file Analyzer.h.
ImageType::Pointer CAnalyzer::m_imageRefContour private
Definition at line 60 of file Analyzer.h.
ImageType::Pointer CAnalyzer::m_imageRefDuplicated private
Definition at line 61 of file Analyzer.h.
ImageType::Pointer CAnalyzer::m_imageTest private
Definition at line 57 of file Analyzer.h.
ImageType::Pointer CAnalyzer::m_imageTestContour private
Definition at line 59 of file Analyzer.h.
ImageType::Pointer CAnalyzer::m_imageTestDuplicated private
Definition at line 62 of file Analyzer.h.
FilterType::Pointer CAnalyzer::m_oFilter private
Definition at line 64 of file Analyzer.h.
itk::ThreadIdType CAnalyzer::m_ThreadNb private
Definition at line 65 of file Analyzer.h.
unsigned int CAnalyzer::m_uiNbLabels private
Number of Labels.
Definition at line 41 of file Analyzer.h.
The documentation for this class was generated from the following files:
C:/dev/fli/tools/SegPerfAnalyzer/src/Analyzer/Analyzer.h
C:/dev/fli/tools/SegPerfAnalyzer/src/Analyzer/Analyzer.cpp