SegPerfAnalyzer: CResults Class Reference
CResults Class Reference
Class to format and saves results.
#include <Results.h>
Public Member Functions
CResults (char *pi_pchBaseFileName)
It is the constructor to used.
~CResults ()
Destructor.
bool save ()
It saves results on text file or xml file in function of class default settings.
bool activeMeasurementOutput (eMesureName pi_eVal)
It active the saving of one specific measure. If it set twice time the effect is inverted.
void setTxt (bool pi_bEnable=true)
Enable or disable text file results.
void setXml (bool pi_bEnable=true)
Enable or disable XML file results.
void setScreen (bool pi_bEnable=true)
Enable or disable on screen results.
void setJaccard (float pi_fVal)
Set the result value of Jaccard measure.
void setDice (float pi_fVal)
Set the result value of Dice measure.
void setSensibility (float pi_fVal)
Set the result value of Sensibility measure.
void setSpecificity (float pi_fVal)
Set the result value of Specificity measure.
void setPPV (float pi_fVal)
Set the result value of PPV (Positive Predictive Value) measure.
void setNPV (float pi_fVal)
Set the result value of NPV (Negative Predictive Value) measure.
void setRVE (float pi_fVal)
Set the result value of Relative volume error.
void setHausdorffDist (float pi_fVal)
Set the result value of DistHausdorff measure.
void setContourMeanDist (float pi_fVal)
Set the result value of contour mean distance measure.
void setAverageSurfaceDist (float pi_fVal)
Set the result value of average surface distance measure.
void setPPVL (float pi_fVal)
Set the result value of PPVL measure.
void setSensL (float pi_fVal)
Set the result value of SensL measure.
void setF1test (float pi_fVal)
Set the result value of F1 score of F-test.
Static Public Member Functions
static char const *const *const getMeasureNameTable ()
Get the list of all Measures available.
Private Member Functions
CResults ()
It is The default constructor.
Private Attributes
float m_fResTab [eMesureLast]
bool m_bResActiveTab [eMesureLast]
bool m_bTxt
bool m_bXml
bool m_bScreen
char * m_pchBaseOutputFileName
Static Private Attributes
static char const *const m_ppchMeasureNameTable [eMesureLast]
Detailed Description
Class to format and saves results.
Definition at line 36 of file Results.h.
Constructor & Destructor Documentation
CResults::CResults (char * pi_pchBaseFileName)
It is the constructor to used.
Parameters
[in] pi_pchBaseFileName Name of the file to evaluate.
Definition at line 54 of file Results.cpp.
References eMesureLast, m_bResActiveTab, m_bScreen, m_bTxt, m_bXml, m_fResTab, and m_pchBaseOutputFileName.
CResults::~CResults ()
Destructor.
It prints the result on screen if necessary.
Definition at line 80 of file Results.cpp.
References eMesureLast, m_bResActiveTab, m_bScreen, m_fResTab, m_pchBaseOutputFileName, m_ppchMeasureNameTable, and MDEL.
CResults::CResults () private
It is The default constructor.
It is private because it must be never used.
Definition at line 38 of file Results.cpp.
References eMesureLast, m_bScreen, m_bTxt, m_bXml, m_fResTab, and m_pchBaseOutputFileName.
Member Function Documentation
bool CResults::activeMeasurementOutput (eMesureName pi_eVal)
It active the saving of one specific measure. If it set twice time the effect is inverted.
Returns
True if file(s) recording are success.
Definition at line 202 of file Results.cpp.
References eMesureLast, and m_bResActiveTab.
Referenced by CSegPerfApp::storeMetricsAndMarks().
char const *const *const CResults::getMeasureNameTable () static
Get the list of all Measures available.
Returns
A constant ordered list of measures names.
Definition at line 219 of file Results.cpp.
References m_ppchMeasureNameTable.
Referenced by CSegPerfApp::about().
bool CResults::save ()
It saves results on text file or xml file in function of class default settings.
Returns
True if file(s) recording are success.
Definition at line 114 of file Results.cpp.
References eMesureLast, m_bResActiveTab, m_bTxt, m_bXml, m_fResTab, m_pchBaseOutputFileName, and m_ppchMeasureNameTable.
Referenced by CSegPerfApp::writeStoredMetricsAndMarks().
void CResults::setAverageSurfaceDist (float pi_fVal) inline
Set the result value of average surface distance measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 178 of file Results.h.
References eMesureDistAverage, and m_fResTab.
Referenced by CSegPerfApp::storeMetricsAndMarks().
void CResults::setContourMeanDist (float pi_fVal) inline
Set the result value of contour mean distance measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 169 of file Results.h.
References eMesureDistMean, and m_fResTab.
Referenced by CSegPerfApp::storeMetricsAndMarks().
void CResults::setDice (float pi_fVal) inline
Set the result value of Dice measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 106 of file Results.h.
References eMesureDice, and m_fResTab.
Referenced by CSegPerfApp::storeMetricsAndMarks().
void CResults::setF1test (float pi_fVal) inline
Set the result value of F1 score of F-test.
Parameters
[in] pi_fVal Measure result value.
Definition at line 205 of file Results.h.
References eMesureF1Test, and m_fResTab.
Referenced by CSegPerfApp::storeMetricsAndMarks().
void CResults::setHausdorffDist (float pi_fVal) inline
Set the result value of DistHausdorff measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 160 of file Results.h.
References eMesureDistHausdorff, and m_fResTab.
Referenced by CSegPerfApp::storeMetricsAndMarks().
void CResults::setJaccard (float pi_fVal) inline
Set the result value of Jaccard measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 97 of file Results.h.
References eMesureJaccard, and m_fResTab.
Referenced by CSegPerfApp::storeMetricsAndMarks().
void CResults::setNPV (float pi_fVal) inline
Set the result value of NPV (Negative Predictive Value) measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 142 of file Results.h.
References eMesureNPV, and m_fResTab.
Referenced by CSegPerfApp::storeMetricsAndMarks().
void CResults::setPPV (float pi_fVal) inline
Set the result value of PPV (Positive Predictive Value) measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 133 of file Results.h.
References eMesurePPV, and m_fResTab.
Referenced by CSegPerfApp::storeMetricsAndMarks().
void CResults::setPPVL (float pi_fVal) inline
Set the result value of PPVL measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 187 of file Results.h.
References eMesurePPVL, and m_fResTab.
Referenced by CSegPerfApp::storeMetricsAndMarks().
void CResults::setRVE (float pi_fVal) inline
Set the result value of Relative volume error.
Parameters
[in] pi_fVal Measure result value.
Definition at line 151 of file Results.h.
References eMesureRelativeVolumeError, and m_fResTab.
Referenced by CSegPerfApp::storeMetricsAndMarks().
void CResults::setScreen (bool pi_bEnable = true) inline
Enable or disable on screen results.
Parameters
[in] pi_bEnable Enable or disable.
Definition at line 88 of file Results.h.
References m_bScreen.
Referenced by CSegPerfApp::storeMetricsAndMarks().
void CResults::setSensibility (float pi_fVal) inline
Set the result value of Sensibility measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 115 of file Results.h.
References eMesureSensibility, and m_fResTab.
Referenced by CSegPerfApp::storeMetricsAndMarks().
void CResults::setSensL (float pi_fVal) inline
Set the result value of SensL measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 196 of file Results.h.
References eMesureSensL, and m_fResTab.
Referenced by CSegPerfApp::storeMetricsAndMarks().
void CResults::setSpecificity (float pi_fVal) inline
Set the result value of Specificity measure.
Parameters
[in] pi_fVal Measure result value.
Definition at line 124 of file Results.h.
References eMesureSpecificity, and m_fResTab.
Referenced by CSegPerfApp::storeMetricsAndMarks().
void CResults::setTxt (bool pi_bEnable = true) inline
Enable or disable text file results.
Parameters
[in] pi_bEnable Enable or disable.
Definition at line 70 of file Results.h.
References m_bTxt.
Referenced by CSegPerfApp::storeMetricsAndMarks().
void CResults::setXml (bool pi_bEnable = true) inline
Enable or disable XML file results.
Parameters
[in] pi_bEnable Enable or disable.
Definition at line 79 of file Results.h.
References m_bXml.
Referenced by CSegPerfApp::storeMetricsAndMarks().
Member Data Documentation
bool CResults::m_bResActiveTab[eMesureLast] private
Table of measurements present in outputs
Definition at line 42 of file Results.h.
Referenced by activeMeasurementOutput(), CResults(), save(), and ~CResults().
bool CResults::m_bScreen private
Enable screen output results format.
Definition at line 45 of file Results.h.
Referenced by CResults(), setScreen(), and ~CResults().
bool CResults::m_bTxt private
Enable txt output results format.
Definition at line 43 of file Results.h.
Referenced by CResults(), save(), and setTxt().
bool CResults::m_bXml private
Enable Xml output results format.
Definition at line 44 of file Results.h.
Referenced by CResults(), save(), and setXml().
float CResults::m_fResTab[eMesureLast] private
Table of measurements results.
Definition at line 41 of file Results.h.
Referenced by CResults(), save(), setAverageSurfaceDist(), setContourMeanDist(), setDice(), setF1test(), setHausdorffDist(), setJaccard(), setNPV(), setPPV(), setPPVL(), setRVE(), setSensibility(), setSensL(), setSpecificity(), and ~CResults().
char* CResults::m_pchBaseOutputFileName private
Base name for output results file.
Definition at line 46 of file Results.h.
Referenced by CResults(), save(), and ~CResults().
char const *const CResults::m_ppchMeasureNameTable static private
Initial value:
=
{
   "Jaccard",
   "Dice",
   "Sensitivity",
   "Specificity",
   "PPV",
   "NPV",
   "RelativeVolumeError",
   "HausdorffDistance",
   "ContourMeanDistance",
   "SurfaceDistance",
   "PPVL",
   "SensL",
   "F1_score"
}
Table to associate a measure name for each measure index defined into eMesureName
Definition at line 48 of file Results.h.
Referenced by getMeasureNameTable(), save(), and ~CResults().
The documentation for this class was generated from the following files:
C:/dev/fli/tools/SegPerfAnalyzer/src/Results/Results.h
C:/dev/fli/tools/SegPerfAnalyzer/src/Results/Results.cpp