SegPerfAnalyzer: itk::SegmentationMeasuresImageFilter< TLabelImage > Class Template Reference
itk::SegmentationMeasuresImageFilter< TLabelImage > Class Template Reference
#include <SegmentationMeasuresImageFilter.h>
Classes
class LabelSetMeasures
Metrics stored per label.
Public Types
typedef
SegmentationMeasuresImageFilter Self
typedef ImageToImageFilter
< TLabelImage, TLabelImage > Superclass
typedef SmartPointer< Self > Pointer
typedef SmartPointer< const Self > ConstPointer
typedef TLabelImage LabelImageType
typedef TLabelImage::Pointer LabelImagePointer
typedef TLabelImage::ConstPointer LabelImageConstPointer
typedef TLabelImage::RegionType RegionType
typedef TLabelImage::SizeType SizeType
typedef TLabelImage::IndexType IndexType
typedef TLabelImage::PixelType LabelType
typedef NumericTraits
< LabelType >::RealType RealType
typedef itksys::hash_map
< LabelType, LabelSetMeasures > MapType
typedef MapType::iterator MapIterator
typedef MapType::const_iterator MapConstIterator
Public Member Functions
itkNewMacro (Self)
itkTypeMacro (SegmentationMeasuresImageFilter, ImageToImageFilter)
itkStaticConstMacro (ImageDimension, unsigned int, TLabelImage::ImageDimension)
void SetSourceImage (const LabelImageType *image)
void SetTargetImage (const LabelImageType *image)
const LabelImageType * GetSourceImage (void)
const LabelImageType * GetTargetImage (void)
MapType GetLabelSetMeasures ()
RealType getSensitivity ()
RealType getSpecificity ()
RealType getPPV ()
RealType getNPV ()
RealType getUnionOverlap ()
RealType getMeanOverlap ()
RealType getRelativeVolumeError ()
RealType getSensitivity (LabelType)
RealType getSpecificity (LabelType)
RealType getPPV (LabelType)
RealType getNPV (LabelType)
RealType getUnionOverlap (LabelType)
RealType getMeanOverlap (LabelType)
RealType getRelativeVolumeError (LabelType)
RealType GetJaccardCoefficient ()
RealType GetDiceCoefficient ()
RealType GetDiceCoefficient (LabelType label)
RealType GetJaccardCoefficient (LabelType label)
Public Attributes
float m_fNbOfPixels
Protected Member Functions
SegmentationMeasuresImageFilter ()
~SegmentationMeasuresImageFilter ()
void PrintSelf (std::ostream &os, Indent indent) const
void AllocateOutputs ()
void BeforeThreadedGenerateData ()
void AfterThreadedGenerateData ()
void ThreadedGenerateData (const RegionType &, ThreadIdType)
void EnlargeOutputRequestedRegion (DataObject *data)
Private Member Functions
SegmentationMeasuresImageFilter (const Self &)
void operator= (const Self &)
Private Attributes
std::vector< MapType > m_LabelSetMeasuresPerThread
MapType m_LabelSetMeasures
Detailed Description
template<typename TLabelImage>
class itk::SegmentationMeasuresImageFilter< TLabelImage >
Definition at line 44 of file SegmentationMeasuresImageFilter.h.
Member Typedef Documentation
template<typename TLabelImage> typedef SmartPointer<const Self> itk::SegmentationMeasuresImageFilter< TLabelImage >::ConstPointer
Definition at line 52 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> typedef TLabelImage::IndexType itk::SegmentationMeasuresImageFilter< TLabelImage >::IndexType
Definition at line 67 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> typedef TLabelImage::ConstPointer itk::SegmentationMeasuresImageFilter< TLabelImage >::LabelImageConstPointer
Definition at line 63 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> typedef TLabelImage::Pointer itk::SegmentationMeasuresImageFilter< TLabelImage >::LabelImagePointer
Definition at line 62 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> typedef TLabelImage itk::SegmentationMeasuresImageFilter< TLabelImage >::LabelImageType
Image related typedefs.
Definition at line 61 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> typedef TLabelImage::PixelType itk::SegmentationMeasuresImageFilter< TLabelImage >::LabelType
Definition at line 69 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> typedef MapType::const_iterator itk::SegmentationMeasuresImageFilter< TLabelImage >::MapConstIterator
Definition at line 123 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> typedef MapType::iterator itk::SegmentationMeasuresImageFilter< TLabelImage >::MapIterator
Definition at line 122 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> typedef itksys::hash_map<LabelType, LabelSetMeasures> itk::SegmentationMeasuresImageFilter< TLabelImage >::MapType
Type of the map used to store data per label
Definition at line 121 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> typedef SmartPointer<Self> itk::SegmentationMeasuresImageFilter< TLabelImage >::Pointer
Definition at line 51 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> typedef NumericTraits<LabelType>::RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::RealType
Type to use for computations.
Definition at line 72 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> typedef TLabelImage::RegionType itk::SegmentationMeasuresImageFilter< TLabelImage >::RegionType
Definition at line 65 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> typedef SegmentationMeasuresImageFilter itk::SegmentationMeasuresImageFilter< TLabelImage >::Self
Standard Self typedef
Definition at line 49 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> typedef TLabelImage::SizeType itk::SegmentationMeasuresImageFilter< TLabelImage >::SizeType
Definition at line 66 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> typedef ImageToImageFilter<TLabelImage, TLabelImage> itk::SegmentationMeasuresImageFilter< TLabelImage >::Superclass
Definition at line 50 of file SegmentationMeasuresImageFilter.h.
Constructor & Destructor Documentation
template<typename TLabelImage > itk::SegmentationMeasuresImageFilter< TLabelImage >::SegmentationMeasuresImageFilter () protected
Definition at line 29 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage> itk::SegmentationMeasuresImageFilter< TLabelImage >::~SegmentationMeasuresImageFilter () inline protected
Definition at line 213 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> itk::SegmentationMeasuresImageFilter< TLabelImage >::SegmentationMeasuresImageFilter (const Self &) private
Member Function Documentation
template<typename TLabelImage > void itk::SegmentationMeasuresImageFilter< TLabelImage >::AfterThreadedGenerateData () protected
Definition at line 84 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage > void itk::SegmentationMeasuresImageFilter< TLabelImage >::AllocateOutputs () protected
Pass the input through unmodified. Do this by setting the output to the source this by setting the output to the source image in the AllocateOutputs() method.
Definition at line 47 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage > void itk::SegmentationMeasuresImageFilter< TLabelImage >::BeforeThreadedGenerateData () protected
Definition at line 58 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage > void itk::SegmentationMeasuresImageFilter< TLabelImage >::EnlargeOutputRequestedRegion (DataObject * data) protected
Definition at line 38 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage> RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::GetDiceCoefficient () inline
Definition at line 189 of file SegmentationMeasuresImageFilter.h.
References itk::SegmentationMeasuresImageFilter< TLabelImage >::getMeanOverlap().
template<typename TLabelImage> RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::GetDiceCoefficient (LabelType label) inline
Definition at line 194 of file SegmentationMeasuresImageFilter.h.
References itk::SegmentationMeasuresImageFilter< TLabelImage >::getMeanOverlap().
template<typename TLabelImage> RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::GetJaccardCoefficient () inline
alternative names
Definition at line 184 of file SegmentationMeasuresImageFilter.h.
References itk::SegmentationMeasuresImageFilter< TLabelImage >::getUnionOverlap().
template<typename TLabelImage> RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::GetJaccardCoefficient (LabelType label) inline
Definition at line 199 of file SegmentationMeasuresImageFilter.h.
References itk::SegmentationMeasuresImageFilter< TLabelImage >::getUnionOverlap().
template<typename TLabelImage> MapType itk::SegmentationMeasuresImageFilter< TLabelImage >::GetLabelSetMeasures () inline
Get the label set measures
Definition at line 156 of file SegmentationMeasuresImageFilter.h.
References itk::SegmentationMeasuresImageFilter< TLabelImage >::m_LabelSetMeasures.
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::getMeanOverlap ()
Definition at line 269 of file SegmentationMeasuresImageFilter.hxx.
Referenced by itk::SegmentationMeasuresImageFilter< TLabelImage >::GetDiceCoefficient().
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::getMeanOverlap (LabelType label)
Definition at line 278 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::getNPV ()
Definition at line 425 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::getNPV (LabelType label)
Definition at line 466 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::getPPV ()
Definition at line 386 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::getPPV (LabelType label)
Definition at line 408 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::getRelativeVolumeError ()
Definition at line 489 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::getRelativeVolumeError (LabelType label)
Definition at line 509 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::getSensitivity ()
tric overlap measuresmeasures over all labels
Definition at line 287 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::getSensitivity (LabelType label)
measures over individual labels
Definition at line 310 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage> const LabelImageType* itk::SegmentationMeasuresImageFilter< TLabelImage >::GetSourceImage (void) inline
Get the source image.
Definition at line 144 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::getSpecificity ()
Definition at line 327 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::getSpecificity (LabelType label)
Definition at line 369 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage> const LabelImageType* itk::SegmentationMeasuresImageFilter< TLabelImage >::GetTargetImage (void) inline
Get the target image.
Definition at line 150 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::getUnionOverlap ()
measures
Definition at line 231 of file SegmentationMeasuresImageFilter.hxx.
Referenced by itk::SegmentationMeasuresImageFilter< TLabelImage >::GetJaccardCoefficient().
template<typename TLabelImage > SegmentationMeasuresImageFilter< TLabelImage >::RealType itk::SegmentationMeasuresImageFilter< TLabelImage >::getUnionOverlap (LabelType label)
Definition at line 252 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage> itk::SegmentationMeasuresImageFilter< TLabelImage >::itkNewMacro (Self)
Method for creation through the object factory.
template<typename TLabelImage> itk::SegmentationMeasuresImageFilter< TLabelImage >::itkStaticConstMacro (ImageDimension , unsigned int, TLabelImage::ImageDimension)
Image related typedefs.
template<typename TLabelImage> itk::SegmentationMeasuresImageFilter< TLabelImage >::itkTypeMacro (SegmentationMeasuresImageFilter< TLabelImage > , ImageToImageFilter)
Runtime information support.
template<typename TLabelImage> void itk::SegmentationMeasuresImageFilter< TLabelImage >::operator= (const Self &) private
template<typename TLabelImage > void itk::SegmentationMeasuresImageFilter< TLabelImage >::PrintSelf (std::ostream & os, Indent indent) const protected
Definition at line 483 of file SegmentationMeasuresImageFilter.hxx.
template<typename TLabelImage> void itk::SegmentationMeasuresImageFilter< TLabelImage >::SetSourceImage (const LabelImageType * image) inline
Set the source image.
Definition at line 132 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> void itk::SegmentationMeasuresImageFilter< TLabelImage >::SetTargetImage (const LabelImageType * image) inline
Set the target image.
Definition at line 138 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage > void itk::SegmentationMeasuresImageFilter< TLabelImage >::ThreadedGenerateData (const RegionType & outputRegionForThread, ThreadIdType threadId) protected
Multi-thread version GenerateData.
Definition at line 122 of file SegmentationMeasuresImageFilter.hxx.
Member Data Documentation
template<typename TLabelImage> float itk::SegmentationMeasuresImageFilter< TLabelImage >::m_fNbOfPixels
Definition at line 125 of file SegmentationMeasuresImageFilter.h.
template<typename TLabelImage> MapType itk::SegmentationMeasuresImageFilter< TLabelImage >::m_LabelSetMeasures private
Definition at line 241 of file SegmentationMeasuresImageFilter.h.
Referenced by itk::SegmentationMeasuresImageFilter< TLabelImage >::GetLabelSetMeasures().
template<typename TLabelImage> std::vector<MapType> itk::SegmentationMeasuresImageFilter< TLabelImage >::m_LabelSetMeasuresPerThread private
Definition at line 240 of file SegmentationMeasuresImageFilter.h.
The documentation for this class was generated from the following files:
C:/dev/fli/tools/SegPerfAnalyzer/src/Analyzer/SegmentationMeasuresImageFilter.h
C:/dev/fli/tools/SegPerfAnalyzer/src/Analyzer/SegmentationMeasuresImageFilter.hxx