SegPerfAnalyzer: CSegPerfApp Class Reference
CSegPerfApp Class Reference
Main class to structure application and handle command line options.
#include <SegPerfApp.h>
Public Member Functions
CSegPerfApp (void)
It is the constructor to used.
~CSegPerfApp (void)
Destructor.
bool init (int argc, char *argv[])
This method set the application behavior thanks to command line arguments parsing.
bool checkParamsChoerancy ()
This method check if command line arguments are coherent between us.
void checkOutputChoerancy ()
This method define an output way if none are defined by command line.
void preparOutput ()
This method define the base file name for output way.
long play ()
This method execute images filter to obtain desired measures, marks and scores.
Static Public Member Functions
static void about ()
This method display information about SegPerfAnalyzer results.
Private Member Functions
void processAnalyze (CAnalyzer &pi_oAnalyzer, int pi_iIndex)
This method provides computing metrics, marks and scores for desired label.
void storeMetricsAndMarks (CResults &pi_roRes)
This method store results into CResults class instance.
long writeStoredMetricsAndMarks (CResults &pi_roRes)
This method flush CResults class instance.
Private Attributes
bool m_bTxt
bool m_bXml
bool m_bScreen
bool m_bSegmentationEvaluation
bool m_bAdvancedEvaluation
bool m_bSurfaceEvaluation
bool m_bLesionsDetectionEvaluation
float m_fSensitivity
float m_fSpecificity
float m_fPPV
float m_fNPV
float m_fDice
float m_fJaccard
float m_fRVE
float m_fHausdorffDist
float m_fMeanDist
float m_fAverageDist
float m_fPPVL
float m_fSensL
float m_fF1
int m_iNbThreads
char * m_pchOutBase
float m_fDetectionLesionMinVolume
float m_fTPLMinOverlapRatio
float m_fTPLMaxFalsePositiveRatio
float m_fTPLMaxFalsePositiveRatioModerator
std::string m_oStrInImage
std::string m_oStrRefImage
std::string m_oStrBaseOut
Detailed Description
Main class to structure application and handle command line options.
Definition at line 17 of file SegPerfApp.h.
Constructor & Destructor Documentation
CSegPerfApp::CSegPerfApp (void)
It is the constructor to used.
Definition at line 22 of file SegPerfApp.cpp.
CSegPerfApp::~CSegPerfApp (void)
Destructor.
It is empty.
Definition at line 76 of file SegPerfApp.cpp.
Member Function Documentation
void CSegPerfApp::about () static
This method display information about SegPerfAnalyzer results.
Definition at line 500 of file SegPerfApp.cpp.
References eMesureLast, and CResults::getMeasureNameTable().
Referenced by detectAboutSwitch().
void CSegPerfApp::checkOutputChoerancy ()
This method define an output way if none are defined by command line.
For the moment the default output way is text file.
Definition at line 282 of file SegPerfApp.cpp.
Referenced by main().
bool CSegPerfApp::checkParamsChoerancy ()
This method check if command line arguments are coherent between us.
If an incoherency is detected into command line arguments a message will be displayed to user and in better cases consistency will be restored.
Definition at line 225 of file SegPerfApp.cpp.
Referenced by main().
bool CSegPerfApp::init (int argc, char * argv[])
This method set the application behavior thanks to command line arguments parsing.
Parameters
[in] argc is the number of command line arguments.
[in] argv is the table of command line arguments.
The main function must delegate to it command line arguments. this method will parse and set different option values.
Definition at line 86 of file SegPerfApp.cpp.
Referenced by main().
long CSegPerfApp::play ()
This method execute images filter to obtain desired measures, marks and scores.
Definition at line 335 of file SegPerfApp.cpp.
References MDEL, and CAnalyzer::setNbThreads().
Referenced by main().
void CSegPerfApp::preparOutput ()
This method define the base file name for output way.
Definition at line 293 of file SegPerfApp.cpp.
Referenced by main().
void CSegPerfApp::processAnalyze (CAnalyzer & pi_roAnalyzer, int pi_iIndex) private
This method provides computing metrics, marks and scores for desired label.
Parameters
[in] pi_roAnalyzer is the reference on the image analyzer class instance.
[in] pi_iIndex is label index.
This method is called by play method.
Definition at line 393 of file SegPerfApp.cpp.
References CAnalyzer::computeAverageSurfaceDistance(), CAnalyzer::computeHausdorffDist(), CAnalyzer::computeITKMeasures(), CAnalyzer::computeMeanDist(), CAnalyzer::getDetectionMarks(), CAnalyzer::getDiceCoefficient(), CAnalyzer::getJaccardCoefficient(), CAnalyzer::getNPV(), CAnalyzer::getPPV(), CAnalyzer::getRelativeVolumeError(), CAnalyzer::getSensitivity(), CAnalyzer::getSpecificity(), CAnalyzer::selectCluster(), CAnalyzer::setDetectionThresholdAlpha(), CAnalyzer::setDetectionThresholdBeta(), CAnalyzer::setDetectionThresholdGamma(), and CAnalyzer::setMinLesionVolumeDetection().
void CSegPerfApp::storeMetricsAndMarks (CResults & pi_roRes) private
This method store results into CResults class instance.
Parameters
[in] pi_roRes is the reference output writer class instance.
This method is called by play method after processAnalyze method.
Definition at line 434 of file SegPerfApp.cpp.
References CResults::activeMeasurementOutput(), eMesureDice, eMesureDistAverage, eMesureDistHausdorff, eMesureDistMean, eMesureF1Test, eMesureJaccard, eMesureNPV, eMesurePPV, eMesurePPVL, eMesureRelativeVolumeError, eMesureSensibility, eMesureSensL, eMesureSpecificity, CResults::setAverageSurfaceDist(), CResults::setContourMeanDist(), CResults::setDice(), CResults::setF1test(), CResults::setHausdorffDist(), CResults::setJaccard(), CResults::setNPV(), CResults::setPPV(), CResults::setPPVL(), CResults::setRVE(), CResults::setScreen(), CResults::setSensibility(), CResults::setSensL(), CResults::setSpecificity(), CResults::setTxt(), and CResults::setXml().
long CSegPerfApp::writeStoredMetricsAndMarks (CResults & pi_roRes) private
This method flush CResults class instance.
Parameters
[in] pi_roRes is the reference output writer class instance.
This method is called by play method after storeMetricsAndMarks method.
Definition at line 491 of file SegPerfApp.cpp.
References CResults::save().
Member Data Documentation
bool CSegPerfApp::m_bAdvancedEvaluation private
Definition at line 30 of file SegPerfApp.h.
bool CSegPerfApp::m_bLesionsDetectionEvaluation private
Definition at line 32 of file SegPerfApp.h.
bool CSegPerfApp::m_bScreen private
Definition at line 24 of file SegPerfApp.h.
bool CSegPerfApp::m_bSegmentationEvaluation private
Definition at line 29 of file SegPerfApp.h.
bool CSegPerfApp::m_bSurfaceEvaluation private
Definition at line 31 of file SegPerfApp.h.
bool CSegPerfApp::m_bTxt private
Definition at line 22 of file SegPerfApp.h.
bool CSegPerfApp::m_bXml private
Definition at line 23 of file SegPerfApp.h.
float CSegPerfApp::m_fAverageDist private
Definition at line 49 of file SegPerfApp.h.
float CSegPerfApp::m_fDetectionLesionMinVolume private
Definition at line 66 of file SegPerfApp.h.
float CSegPerfApp::m_fDice private
Definition at line 41 of file SegPerfApp.h.
float CSegPerfApp::m_fF1 private
Definition at line 55 of file SegPerfApp.h.
float CSegPerfApp::m_fHausdorffDist private
Definition at line 47 of file SegPerfApp.h.
float CSegPerfApp::m_fJaccard private
Definition at line 42 of file SegPerfApp.h.
float CSegPerfApp::m_fMeanDist private
Definition at line 48 of file SegPerfApp.h.
float CSegPerfApp::m_fNPV private
Definition at line 40 of file SegPerfApp.h.
float CSegPerfApp::m_fPPV private
Definition at line 39 of file SegPerfApp.h.
float CSegPerfApp::m_fPPVL private
Definition at line 53 of file SegPerfApp.h.
float CSegPerfApp::m_fRVE private
Definition at line 43 of file SegPerfApp.h.
float CSegPerfApp::m_fSensitivity private
Definition at line 37 of file SegPerfApp.h.
float CSegPerfApp::m_fSensL private
Definition at line 54 of file SegPerfApp.h.
float CSegPerfApp::m_fSpecificity private
Definition at line 38 of file SegPerfApp.h.
float CSegPerfApp::m_fTPLMaxFalsePositiveRatio private
Definition at line 68 of file SegPerfApp.h.
float CSegPerfApp::m_fTPLMaxFalsePositiveRatioModerator private
Definition at line 69 of file SegPerfApp.h.
float CSegPerfApp::m_fTPLMinOverlapRatio private
Definition at line 67 of file SegPerfApp.h.
int CSegPerfApp::m_iNbThreads private
Definition at line 60 of file SegPerfApp.h.
std::string CSegPerfApp::m_oStrBaseOut private
Definition at line 74 of file SegPerfApp.h.
std::string CSegPerfApp::m_oStrInImage private
Definition at line 72 of file SegPerfApp.h.
std::string CSegPerfApp::m_oStrRefImage private
Definition at line 73 of file SegPerfApp.h.
char* CSegPerfApp::m_pchOutBase private
Definition at line 61 of file SegPerfApp.h.
The documentation for this class was generated from the following files:
C:/dev/fli/tools/SegPerfAnalyzer/src/SegPerfApp.h
C:/dev/fli/tools/SegPerfAnalyzer/src/SegPerfApp.cpp