SegPerfAnalyzer: C:/dev/fli/tools/SegPerfAnalyzer/src/main.cpp File Reference
main.cpp File Reference
Contains the main function.
#include "SegPerfApp.h"
Functions
bool detectAboutSwitch (int argc, char **argv)
This function detect and applies the "about" command line switch before TCLAP.
int main (int argc, char **argv)
Application entry point.
Detailed Description
Contains the main function.
Author
Florent LERAY
Baptiste LAURENT
Date
13/04/2016
Version
2.1
Definition in file main.cpp.
Function Documentation
bool detectAboutSwitch (int argc, char ** argv)
This function detect and applies the "about" command line switch before TCLAP.
Parameters
[in] argc is the number of command line arguments.
[in] argv is the table of command line arguments.
Returns
true if "About switch" is find on command line
Definition at line 18 of file main.cpp.
References CSegPerfApp::about().
Referenced by main().
int main (int argc, char ** argv)
Application entry point.
Parameters
[in] argc is the number of command line arguments.
[in] argv is the table of command line arguments.
Returns
positive value in success or -1 if field to write all measures .
Definition at line 53 of file main.cpp.
References CSegPerfApp::checkOutputChoerancy(), CSegPerfApp::checkParamsChoerancy(), detectAboutSwitch(), CSegPerfApp::init(), CSegPerfApp::play(), and CSegPerfApp::preparOutput().